import os
import uuid

def process_message(message: str) -> str:
    """
    ユーザーからのメッセージを処理し、タスクを実行して応答を生成する
    """
    if "python" in message.lower() and ("create" in message.lower() or "作成" in message.lower() or "作って" in message.lower()):
        return create_python_script(message)
    else:
        return f"AIが応答します: 「{message}」について、どのような処理をご希望ですか？具体的な指示（例：「『ハローワールド』と表示するPythonスクリプトを作成して」）をいただけると、コードを生成できます。"

def create_python_script(instruction: str) -> str:
    """
    簡単なPythonスクリプトを生成し、ファイルに保存する
    """
    # NOTE: This is a mock implementation.
    # In a real scenario, an LLM would generate this code based on the instruction.
    code_content = '# This script was generated by Jidoka AI Agent\n\nprint("Hello from Jidoka!")'
    
    # Create a unique filename
    filename = f"script_{uuid.uuid4().hex[:8]}.py"
    workspace_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'workspace')
    
    if not os.path.exists(workspace_dir):
        os.makedirs(workspace_dir)
        
    file_path = os.path.join(workspace_dir, filename)

    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(code_content)
        
        response_message = f"承知しました。簡単なPythonスクリプト `{filename}` を `workspace` ディレクトリに作成しました。中身を確認してください。"
        return response_message
    except Exception as e:
        return f"ファイルの作成中にエラーが発生しました: {e}" 